Some improvements in autocompletion
mattermost/mattermost-plugin-cloud pull request #163
Opened 2024-11-27 18:23 UTC by jespino

#### Summary
Adding the icon, and fixing some of the autocompletion for names of instances. Also I still have other improvemtns to do like allow to select specific otpions for specific flags.

```release-note
None
```

2024-11-27 18:38 UTC, jespino commented
This time I also tested it locally (I was able to test it with a ton of fake configuration, because I'm only testing the autocompletion)

2024-11-28 18:19 UTC, nickmisasi approved these changes

2024-12-02 14:09 UTC, gabrieljackson requested changes
Looks great, just found a few help texts that need a small tweak.

2024-12-02 14:09 UTC, gabrieljackson commented on server/command.go
> +										HelpText: "Mini Singleton cluster",
```suggestion
										HelpText: "Mini cluster made of two servers",
```

2024-12-02 14:09 UTC, gabrieljackson commented on server/command.go
> +										HelpText: "Mini Singleton cluster",
```suggestion
										HelpText: "Mini cluster made of two servers",
```

2024-12-02 14:09 UTC, gabrieljackson commented on server/command.go
> +										HelpText: "RDS Postgres with pgbouncer proxy connections",
```suggestion
										HelpText: "Shared S3 bucket with access via bifrost",
```

2024-12-02 16:07 UTC, gabrieljackson approved these changes
Looks great! Thanks!

2024-12-02 16:31 UTC, merged